name: preflight

services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: ./docker
    entrypoint: ./docker-web-entrypoint.sh
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/preflight
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
